name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ 1.17 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Set git to use LF
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit linting
        if: matrix.os == 'ubuntu-latest' && github.ref != 'refs/heads/master'
        uses: wagoid/commitlint-github-action@v2
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Build
        run: make build
      - name: Vet
        if: matrix.os == 'ubuntu-latest'
        run: make vet
      - name: Tests
        run: make test
